server:
  servlet:
    context-path: /document
  port: 8084
spring:
  thymeleaf:
    suffix: .html
    prefix: classpath:/templates/
  datasource:
    url: jdbc:h2:mem:document
    driverClassName: org.h2.Driver
    username: document
    password: document
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true